### ISSUE TITLE
Why does it throw an exception on duplicate record? Why not just fail silently?

### ISSUE THREAD

**Issue by davereid** [e0ipso/queue_unique#2]
I'm curious why this throws an exception on trying to insert a duplicate item. I would think that the desired behavior would be to fail silently (since the first item is still in the queue, it will get processed), or to update the 'created' value using db_merge() of the existing item in the queue.

Maybe we can just change the db_insert() into a db_merge() for now? That would avoid the PDO exceptions.

**Comment by e0ipso** [comment]
My thoughts around this is that the application could want to react to the fact that they are trying to push a duplicated item to a unique queue. Something like giving them the opportunity to say «Hey you! This item is not unique, I did nothing with it.»

**Comment by davereid** [comment]
Hrm, I guess I haven't seen an established pattern of looking for exceptions with adding items to queues around modules in Drupal 7. The docs for SystemQueue::createItem() (which this is supposed to be a drop-in replacement for) says:

> @return bool
>   TRUE if the item was successfully created and was (best effort) added to
>   the queue, otherwise FALSE. We don't guarantee the item was committed to
>   disk etc, but as far as we know, the item is now in the queue.

I think this changes that expectation.

**Comment by e0ipso** [comment]
That is a good point @davereid. I will fix this and convey that information by returning a boolean.

I feel that Drupal is letting me down on this one, making me surface errors to the top manually instead of letting an exception propagate until the appropriate catch.

**Comment by e0ipso** [comment]
This has been fixed in https://github.com/e0ipso/queue_unique/commit/2ad73cde2b91fb783214a5a89cbf54896136620e.

Thanks again for your thoughts on this @davereid.
