### ISSUE TITLE
PDOException not caught with only return FALSE;

### ISSUE THREAD

**Issue by minorOffense** [e0ipso/queue_unique#3]
When the PDOException is thrown it isn't always caught by the catch statement since we don't do anything with the $e variable.

(It's annoying and dumb I know).

To ensure it's always caught, we should call ``unset($e);`` before the ``return FALSE;`` so that PHP doesn't skip over the catch call.

It's an issue for me at least in Drupal 7 getting duplicate key exceptions with the md5 key.

http://stackoverflow.com/questions/4820211/catch-an-exception-without-doing-anything-in-the-catch

**Comment by minorOffense** [comment]
And so far I don't have a solution that works...

**Comment by darthsteven** [comment]
That sort of sounds like your PHP is buggy? If there's a PDOExection, PHP should catch it, otherwise, I don't trust that `1 + 1 = 2` any more.

**Comment by e0ipso** [comment]
Closing after years without progress on this.
