### ISSUE TITLE
Drupal 8 port?

### ISSUE THREAD

**Issue by kasperg** [e0ipso/queue_unique#4]
Would you have any interest in a port of this module to Drupal 8?

**Comment by e0ipso** [comment]
I don't think I have any client that needs this module at the moment. I don't think I'll port it unless someone steps up to sponsor the port.

Mateu Aguiló Bosch.

-------- Original Message --------
On Feb 6, 2019, 4:18 PM, Kasper Garnæs wrote:

Mateu Aguiló Bosch.

-------- Original Message --------

**Comment by kasperg** [comment]
I did not mean for you to do the port 😅. 

I have been working on a port and wondered if you would be interested in including it as a part of your module or you prefer to keep things as is.

**Comment by e0ipso** [comment]
Lol. That'd be awesome. How do you want to coordinate?

**Comment by kasperg** [comment]
Cool. If you create a branch (8.x-2.x?) then I can open a PR against that and we can continue the discission there?

**Comment by e0ipso** [comment]
Done!

Let's move the conversation to the (incoming) PR.
